add: header, logo, main.css
georgesh08/eastwest-web pull request #1
Opened 2022-09-24 09:50 UTC by georgesh08

2022-10-03 11:19 UTC, BakasaRus requested changes
1. Какой-нибудь арт закинуть бы... Можно даже закинуть какой-нибудь флаг
2. С кодом аналогично
3. С цитатой и формулой успеха аналогично
4. Со стилями текста аналогично

2022-10-03 11:19 UTC, BakasaRus commented on index.html
> +    <link href="css/main.css" rel="stylesheet">
Ключевых слов бы добавить ещё

2022-10-09 20:55 UTC, BakasaRus requested changes

2022-10-09 20:55 UTC, BakasaRus commented on index.html
> +    <meta charset="utf-8" name="keywords" content="язык, клуб, обучение, спб">
Это не так работает, нужен отдельный тег `<meta/>`

2022-10-09 20:55 UTC, BakasaRus commented on index.html
> +        </code>
Зачем тут `<br>`?

2022-10-09 20:57 UTC, georgesh08 commented on index.html
> +        </code>
без него не форматируется нормально код

2022-10-09 21:05 UTC, georgesh08 commented on index.html
> +        </code>
а, кажется осознал в чем не прав

2022-11-14 11:01 UTC, BakasaRus approved these changes

2022-11-27 14:22 UTC, merged